name: Publish Docker image

on:
  push:
    branches: [ master, feature-*, spike-* ]
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push yaitde-agent to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v2.x

      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile-npm
          push: true
          tags: |
            ghcr.io/yaitde/yaitde-agent:${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }} 
          secrets: |
            SIGNING_KEY=${{ secrets.SIGNING_KEY }}
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}

      - name: Notify automation that the image is ready
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: 
            '{ "buildId": "${{ github.run_number }}", "applicationName" : "${{ env.GITHUB_REF_SLUG }}", "imagePath" : "ghcr.io/yaitde/yaitde-agent:${{ env.GITHUB_REF_SLUG }}-${{ github.run_number }}" }'
